### ISSUE TITLE
Mount local crates into container

### ISSUE THREAD

**Issue by stuartnelson3** [emk/rust-musl-builder#25]
Would you be interested in adding a note to the README about mounting the local cache to speed up build times? It stores the crates on the host machine in-between builds, and speeds up the overall build process.

```bash
# CACHE_DIR is probably $HOME/.cargo/registry

docker run --rm -it -v $CACHE_DIR:/home/rust/.cargo/registry -v $(pwd):/home/rust/src ekidd/rust-musl-builder:nightly cargo build
```

**Comment by emk** [comment]
Interesting idea!

I'm a bit reluctant to officially document this, because it seems like the kind of thing which might result in more support requests. `rust-musl-builder` is maintained, and it's used by several projects, but I'm less interested in adding new features.

I think there's a more ambitious Docker-based building setup out there, which might be worth looking into if you need something fancier.

**Comment by stuartnelson3** [comment]
Cool, no worries!
