### ISSUE TITLE
replace deprecated openssl-sys by rust-openssl?

### ISSUE THREAD

**Issue by dvic** [emk/rust-musl-builder#46]
I read on https://github.com/alexcrichton/openssl-sys that it's deprecated and that one should  use https://github.com/sfackler/rust-openssl. Would rust-openssl work here?

**Comment by emk** [comment]
It's possible that it might already work!

If it doesn't, we really ought to support it. But updating new libraries can be a pretty time-consuming process. And in any case, we can't stop supporting `openssl-sys`, because I'm sure plenty of people are still using it.

If anybody wants to look into this, I'm happy to answer questions. I probably won't be able to get to it right away myself.

**Comment by dvic** [comment]
Fixed in #48

**Comment by emk** [comment]
Thank you for the patches! I merged them and updated the README, and they should be building now.
