### ISSUE TITLE
Is README out of date for nightly tags?

### ISSUE THREAD

**Issue by sentient-abanchich** [emk/rust-musl-builder#79]
Running with a date in the tag does not work for me:

```
docker run --rm -it -v "$(pwd)":/home/rust/src -v cargo-git:/home/rust/.cargo/git -v cargo-registry:/home/rust/.cargo/registry -v target:/home/rust/src/target ekidd/rust-musl-builder:nightly-2019.08.01

Unable to find image 'ekidd/rust-musl-builder:nightly-2019.08.01' locally
docker: Error response from daemon: manifest for ekidd/rust-musl-builder:nightly-2019.08.01 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

Running this without a date in the tag (not show in the README) does work:

```
docker run --rm -it -v "$(pwd)":/home/rust/src -v cargo-git:/home/rust/.cargo/git -v cargo-registry:/home/rust/.cargo/registry -v target:/home/rust/src/target ekidd/rust-musl-builder:nightly
```

**Comment by sentient-abanchich** [comment]
Also wondering about the `Making OpenSSL work` section of the README. I am using `reqwest` in my crate and hitting `https` endpoints but I didn't have to do anything with `openssl_probe`; it just worked.

**Comment by emk** [comment]
My policy for nightly images has changed a bit:

- There is no more generic `nightly` tag, because it only got rebuilt once every few weeks, and it was often built using a broken version.
- I do periodically build specific nightly images, checking [this page](https://rust-lang.github.io/rustup-components-history/index.html) to make sure that I'm including both `clippy` and `rls`. You can find a list of nightly tags [here](https://hub.docker.com/r/ekidd/rust-musl-builder/tags). This will not be every nightly image. Also note that `nightly-2019.08.01` wouldn't work, because we use `rustup` syntax, which would be `nightly-2019-08-01`.

If there's a specific newer nightly image that you'd like a tagged build for, please feel free to file an issue.

> Also wondering about the Making OpenSSL work section of the README. I am using reqwest in my crate and hitting https endpoints but I didn't have to do anything with openssl_probe; it just worked.

Generally speaking, if you don't include `openssl_probe`, your static binaries will fail on various Linux distros.

**Comment by sentient-abanchich** [comment]
Ah, that explains it! I was using the `nightly-2019-08-01` syntax too but just needed the list of Docker tags.

Thanks!
